git fetch --deepen=50

diff --git a/.github/workflows/create-new-release.yml b/.github/workflows/create-new-release.yml
--- a/.github/workflows/create-new-release.yml
+++ b/.github/workflows/create-new-release.yml
@@ -15,21 +15,30 @@ jobs:
 
       - name: Test available
         run: |
-          git fetch -n origin '+refs/heads/releases/*:refs/remotes/origin/releases/*'
+          # shallow fetch releases/* branches
+          git fetch -n --depth=1 origin '+refs/heads/releases/*:refs/remotes/origin/releases/*'
+
+          while true; do
+              # try `git merge-base`
+              for branch in $(git for-each-ref --format='%(refname:short)' 'refs/remotes/origin/releases/*'); do
+                  BASE_COMMIT=$(git merge-base main $branch) || continue 2
+              done
+
+              # if success all branches
+              break
+
+              # failed on git merge-base, fetch more history
+              git fetch --deepen=50 origin main '+refs/heads/releases/*:refs/remotes/origin/releases/*'
+          done
 
           for branch in $(git for-each-ref --format='%(refname:short)' 'refs/remotes/origin/releases/*'); do
-            echo ${branch#origin/}
-            git merge-base main ${branch#origin/}
-            base_commit=$(git merge-base main ${branch#origin/})
-            base_commit_time=$(git log -1 --format="%at" $base_commit)
-            current_commit_time=$(git log -1 --format="%at" $GITHUB_SHA)
-            echo $base_commit
-            echo $GITHUB_SHA
+              base_commit=$(git merge-base main $branch)
+              base_commit_time=$(git log -1 --format="%at" $base_commit)
+              current_commit_time=$(git log -1 --format="%at" $GITHUB_SHA)
 
-            if [ $base_commit_time -ge $current_commit_time ]; then
-              echo 'exit 1'
-              exit 1
-            fi
+              if [ $base_commit_time -ge $current_commit_time ]; then
+                  exit 1
+              fi
           done
 
       - name: Calculate new version
